### ISSUE TITLE
csvy

### ISSUE THREAD

**Issue by ijlyttle** [uncoast-unconf/steward#65]
In general, our yaml format should hew to (or perhaps be a lightweight version of) the [table-schema](http://frictionlessdata.io/specs/table-schema/) used by [csvy](https://csvy.org/).

- [x] refer to this in README (#66)
- [x] the `source` field in `stw_meta`to be renamed `sources`, a data-frame with columns `title`, `path`, `email`. (#67)
- [ ] the yaml reading and writing to refer to a `schema` element with a `fields` sub-element. It will use generic values for `type`: `"boolean"`, `"integer"`, ... . We will have to translate to R types. In the future, we can consider factors. (#68)
